### ISSUE TITLE
Disney-Pixar Up (high-end versions) crash when playing sound effects and other issues

### ISSUE THREAD

**Issue by TwoSpacesSG** [TASEmulators/freej2me-plus#20]
Full list of issues I've noticed in this game:
- Sony Ericsson K800i and K850i versions crash when picking up the balloon in the first level. This is likely sound effect related.
- Sony Ericsson K800i version and Nokia N95 version don't display transparency on the tutorial screens correctly.
- Nokia N95 version doesn't display the "Enable sound?" screen, it's a white screen instead.
- Nokia N95 version crashes with a different error when picking up a balloon or sometimes when picking up a tutorial box.

**Comment by AShiningRay** [comment]
Audio issues haven't been a problem in this game after the recent PlatformPlayer improvements. And the latest commits aimed at PlatformGraphics have fixed the visual issues as well, though i'm not sure what commit exactly fixed it as i wasn't exactly testing them against UP. Could be any of these: e2e44ef7dcc5e61cb6aad34b36c1cd89c32a5bc6, 4e12a6ce3677c6f2ff651684853795ca415e4516 (though it should be nokia-only), 20fb8b7aa037b29cc7ea62464fccd97853aba22e

So i'm closing this one.
