### ISSUE TITLE
CI artifacts from pull requests fail to get uploaded

### ISSUE THREAD

**Issue by vadosnaprimer** [TASEmulators/freej2me-plus#22]
https://github.com/TASEmulators/freej2me-plus/actions/runs/11212278346/job/31841764779?pr=15

> Error: The artifact name is not valid: freej2me-refs/pull/15/merge-dc15112. Contains the following character:  Forward slash /

**Comment by AShiningRay** [comment]
That's uh... not a bug in the tree. You're trying to run a build from a branch that now has conflicts with the main tree (gotta thank the major sound system rewrite for that), hence the weird artifact name, as it can't just rebase it automatically into the tree to follow through.

**Comment by vadosnaprimer** [comment]
Oh! Thanks!

**Comment by vadosnaprimer** [comment]
Hmm same issue with [another PR](https://github.com/TASEmulators/freej2me-plus/actions/runs/11486015111/job/31967385543?pr=23), again the problem is having a slash in the name. The build is fine this time.

**Comment by AShiningRay** [comment]
> Hmm same issue with [another PR](https://github.com/TASEmulators/freej2me-plus/actions/runs/11486015111/job/31967385543?pr=23), again the problem is having a slash in the name. The build is fine this time.

Eh, i'd just ignore the final result of the CI, as it tries to publish artifacts as well. If the build step goes through, that's all that matters as far as the CI check is concerned.

**Comment by vadosnaprimer** [comment]
The good thing about PR artifacts is ability to test them right away, and even people without build env can do it. So I'd say it's valuable.
