### ISSUE TITLE
How do you make the freej2me-plus core work on Windows 11 retroarch?

### ISSUE THREAD

**Issue by andjao** [TASEmulators/freej2me-plus#39]
Can anyone give me a step-by-step guide to how it works? because I can't play any j2me games.

**Comment by vadosnaprimer** [comment]
- Install Java Runtime Environment, for example from https://www.java.com/en/download/manual.jsp
- Double-click freej2me.jar
- Use File menu to open a J2ME game

**Comment by raidenii** [comment]
* Get [OpenJDK JRE](https://adoptium.net/temurin/releases/?os=windows&arch=x64&package=jre), don't use Oracle JRE.
* Get latest builds of both jar and libretro core from nightly.link, links are in the top part of README.
* Extract freej2me-lr.jar into system folder, and freej2me_libretro.dll into cores folder.
* Load J2ME games.

**Comment by AShiningRay** [comment]
Given that this has been explained thoroughly, and that, hopefully, FreeJ2ME-Plus will integrate Libretro's official list of cores at some point, i don't see a reason to keep this issue open.

Closing as i don't think any further discussion is needed.
