### ISSUE TITLE
Nokia Tones are not supported yet

### ISSUE THREAD

**Issue by AShiningRay** [TASEmulators/freej2me-plus#40]
This is just a note for later. Nokia OTT/OTA tones aren't implemented at all. I reckon it should follow the current implementations for Siemens MelodyComposer and Sprintpcs + Bell DualTone, by converting the incoming byte array into midi (using the Square Wave instrument)... this would make it so every single tone implementation uses the main audio handler, PlatformPlayer, as a base, dodging most of the code duplication that would have to happen, and helping maintenance quite a bit.

**Comment by SergioFLS** [comment]
For reference, this document somewhat describes the format: https://affon.narod.ru/GSM/ssm200.pdf (see 3.8 Ringing Tones)

There's also a parser in AOSP's sonivox: https://github.com/pedrolcl/sonivox/blob/290e469a8fd4871413e4c544f7820650c36bc056/arm-wt-22k/lib_src/eas_ota.c

**Comment by AShiningRay** [comment]
> For reference, this document somewhat describes the format: https://affon.narod.ru/GSM/ssm200.pdf (see 3.8 Ringing Tones)
> 
> There's also a parser in AOSP's sonivox: https://github.com/pedrolcl/sonivox/blob/290e469a8fd4871413e4c544f7820650c36bc056/arm-wt-22k/lib_src/eas_ota.c

Yep, those have come to my attention a while ago, and i've actually come across a newer revision of that Smart Messaging Specification that also contains a ringing tone decode example as well, [which can be found here, at section 5.1.5](http://customer.intele.no/files/Smart_Messaging_Specification_rev_3_0_0.pdf)

I just need to find some time to focus exclusively on this.

**Comment by TwoSpacesSG** [comment]
MIDI playback using Nokia Sound (seen in Micro Machines for Nokia 176x208 for example) doesn't seem to be implemented either.

**Comment by AShiningRay** [comment]
Fixed by 5ee104456945ab696f8dbc5884b8a81f46eb2a69, 5946959c4b2270a99c7876849548f788eb8a6c85, 6eb05b819664bc5e8de3d45a28e6b7245fb52f47 and 8fed7ebc2e066ab2f0424a5f49ea9b06bab398f4
