### ISSUE TITLE
Fail to launch games with local installation JADs

### ISSUE THREAD

**Issue by TwoSpacesSG** [TASEmulators/freej2me-plus#43]
For example when the game is called "Game.jar" and in the JAD it says: "MIDlet-Jar-URL: Game.jar". Usually what happens on phones is that the phone looks for a jar with this name in the same folder and installs it, but currently in freej2me-plus this results in an error, even though by intention, choosing the JAR should grab info from the JAD and launch the JAR.

**Comment by AShiningRay** [comment]
Should have been fixed by 0440d496afe32fa6cfd2ae67d60209ba50b58db4

**Comment by TwoSpacesSG** [comment]
Yeah, looks like it's fixed
