### ISSUE TITLE
Heroes Lore: Wind of Soltia has serious input lag issues

### ISSUE THREAD

**Issue by AShiningRay** [TASEmulators/freej2me-plus#7]
Version: (Nokia E71, 320x240, md5: e4e36ddb3da327c6d289c65ec48e86f5) [Reproducible in all versions as far as i know]

This is a bit of a weird one, there's so many interrupts going on in the game, that inputs basically get queued for a long time before being processed. This behavior becomes increasingly noticeable the more you interact with the app. 

zb3's EventQueue code for key presses helped bring that up, although i'm not sure what could be done to work around cases like these at the moment, inputs really shouldn't run completely uninterrupted either.

**Comment by TwoSpacesSG** [comment]
May be the same issue in Ratatouille (not to be confused with Ratatouille: Cheese Rush).
